# Generated by Django 5.1.7 on 2025-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_aniversario_alter_cliente_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aniversario',
            field=models.CharField(help_text='Formato: DD/MM', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
