# Generated by Django 5.1.7 on 2025-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_aniversario_alter_cliente_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aniversario',
            field=models.DateField(blank=True, help_text='Formato: dd/mm/yyyy', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
