# Generated by Django 5.1.7 on 2025-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_aniversario_alter_cliente_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(max_length=30),
        ),
    ]
