# Generated by Django 5.1.7 on 2025-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
