# Generated by Django 5.1.7 on 2025-05-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aniversario',
            field=models.CharField(blank=True, help_text='Formato: dd/mm', max_length=5, null=True),
        ),
    ]
