# Generated by Django 5.1.7 on 2025-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'À Vista'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária'), ('outro', 'Outro')], default='avista', max_length=20, null=True),
        ),
    ]
