# Generated by Django 5.1.7 on 2025-09-24 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('À Vista', 'À Vista'), ('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Transferência Bancária', 'Transferência Bancária'), ('Outro', 'Outro')], default='avista', max_length=60, null=True),
        ),
    ]
